version: '3'

services:
    db:
      image: postgres:16
      restart: always
      ports: 
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: postgres
        POSTGRES_DB: nest-ecommerce
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: